# Generated by Django 2.2.1 on 2019-05-16 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190514_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='taxi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Taxi'),
        ),
    ]
