# Generated by Django 2.2.1 on 2019-05-16 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190516_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='taxi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Taxi'),
        ),
    ]
