# Generated by Django 2.2.1 on 2019-05-20 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190516_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='taxi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Taxi'),
        ),
    ]
