# Generated by Django 2.2.1 on 2019-05-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='taxi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Taxi'),
        ),
    ]
