# Generated by Django 2.2.1 on 2019-05-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190515_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash')], default='cash', max_length=10),
            preserve_default=False,
        ),
    ]
